### ISSUE TITLE
DBus Notifications only work once (at least on X11)

### ISSUE THREAD

**Issue by Okabintaro** [galister/X11Overlay#11]
I noticed that DBus Notifications only fire once when using X11.
After the first notification arrives it seems that the DBus Listener crashes and doesn't work anymore.
Did some debugging and it seems that you will have to connect to DBus explicitly to make the Observer/Rule matcher work continuously: 
![image](https://user-images.githubusercontent.com/103938900/231775822-680fa230-b5fc-478d-b7ba-1d609b80b588.png)

I tried to do that quickly in the [NotificaionManager.RegisterDbusAsync()](https://github.com/galister/WlxOverlay/blob/bebd9ad32b2ac80ea253536ac9b5d1166641cf96/Core/NotificationsManager.cs#L76) but it doesn't seem to work:

```diff
...
    private async Task RegisterDbusAsync()
    {
        var dbus = Connection.Session;
+       await dbus.ConnectAsync();

        var rule = new MatchRule
        {
            Member = "Notify",
            Interface = "org.freedesktop.Notifications",
            Path = "/org/freedesktop/Notifications",
            Type = MessageType.MethodCall,
            Eavesdrop = true
        };
...
```

**Comment by galister** [comment]
see if it's better with https://github.com/galister/WlxOverlay/commit/9e93b01225f0478d402466131e38853baa27e27d

**Comment by Okabintaro** [comment]
Seems to work and fixed now. Thanks!

**Comment by VRcontrib** [comment]
Thank you for fixing this!
