### ISSUE TITLE
Resetting the playspace mover offest via the wristwatch sets the offset to the wrong location.

### ISSUE THREAD

**Issue by VRcontrib** [galister/X11Overlay#15]
When I use the playspace mover's "Reset Offset" button, I get moved under the floor and to the west of the real playspace. fixing the floor does not reset it to the proper position either. Restarting SteamVR doesn't fix the incorrect offset, the only way to fix it is to redo room setup. I've tested this on both stable and beta SteamVR with the same result (SteamVR beta is shown in the video.) Here's a video of what's happening (the polygons I create are in the same spot on the edge of my desk IRL): [Video](https://drive.proton.me/urls/Z2ZKAS22QW#ll1uzxNcTkWz)

Sorry for the compression, I used telegram to send the video file from my vr computer to my laptop.

**Comment by galister** [comment]
The idea is to use it in conjunction with `Make Default`. You can use `Make Default` and then load back that default state with reset offset. I was under the impression that SteamVR would reset you to the center of the playspace if you were to use it without `Make Default` first (as the pose would be an identity matrix).

I guess the solution is to gray out the button  when a `Make Default` is not set?

**Comment by galister** [comment]
Just to confirm, if you've used `Make Default` then you get the intended behavior?

**Comment by VRcontrib** [comment]
Yes, that does work. Thank you for the help!

However, while I was doing some more testing I realized it doesn't move the entire playspace, just the user. Shouldn't the behavior be to actually move the entire playspace instead of just the user? Wherever you set `Make Default`, the playspace will still never match up with the real world playspace unless you are standing in the exact same position in the room that you used `Make Default` in. [OpenVR-AdvancedSettings](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings) does it by moving the entire playspace, so it always matches with the real playspace, and they also don't have the jittery movement issue.

Should I open a new [Feature Request] issue for that?

**Comment by VRcontrib** [comment]
I could also attach a video of what I'm talking about, if that would be helpful.

**Comment by galister** [comment]
I get the same jitter with OVRAS on Linux, so I believe it's a Linux-specific issue. By entire playspace you mean the drawn lines as well? I haven't implemented that yet, but it's quick enough to do.

**Comment by VRcontrib** [comment]
> I get the same jitter with OVRAS on Linux, so I believe it's a Linux-specific issue

That's really weird, I don't get that issue with ovras on my system.

> By entire playspace you mean the drawn lines as well? I haven't implemented that yet, but it's quick enough to do.

Yeah, sorry, that is what I mean. Thank you!

**Comment by galister** [comment]
fix is on master. master might have other issues though (big refactor), so any testing is welcome.

**Comment by VRcontrib** [comment]
Thank you! I'll do some testing on master soon and report any issues I find.
