### ISSUE TITLE
`EGL_NO_DISPLAY` returned when `WAYLAND_DISPLAY` is unset upon running

### ISSUE THREAD

**Issue by KiyoNetcat** [galister/X11Overlay#16]
OS: Arch Linux 6.4.3-zen1-2-zen
DE: KDE Plasma (Wayland)
GPU: Nvidia GTX 1070 running on latest `nvidia-dkms` drivers (535.54.03-1)

Running WlxOverlay with `WAYLAND_DISPLAY` unset causes `eglGetDisplay` to return `EGL_NO_DISPLAY`. I get the same error even if I override `WAYLAND_DISPLAY` to `wayland-0` (output of `echo $WAYLAND_DISPLAY` for me) in the `config.yml` file.

Here's the output when I try to run it:
```
WlxOverlay v1.3.1
OpenVR Version: 1.26.6
IVROverlay_025: pass
IVRCompositor_027: pass
IVRInput_010: pass
Loaded 10 input actions for /actions/default
export_inputs will not be used.
HMD running @ 90 Hz
Wayland detected.
eglGetPlatformDisplayEXT returned EGL_NO_DISPLAY!
eglGetDisplay returned EGL_NO_DISPLAY!
Unhandled exception. System.ApplicationException: Could not get EGL display!
   at WlxOverlay.Desktop.EGL.Initialize() in /home/runner/work/WlxOverlay/WlxOverlay/Desktop/EGL.cs:line 44
   at WlxOverlay.Desktop.Wayland.WaylandInterface.TryInitialize() in /home/runner/work/WlxOverlay/WlxOverlay/Desktop/Wayland/WaylandInterface.cs:line 53
   at Program.<Main>$(String[] args) in /home/runner/work/WlxOverlay/WlxOverlay/Program.cs:line 80
   at Program.<Main>(String[] args)
```

I see that the `master` branch may have a fix for this already, however, I'm unable to compile it due to `StereoKit` being missing from the `/lib` directory.

**Comment by galister** [comment]
try build now.
