### ISSUE TITLE
Oversized pointer in WlxOverlay v1.4.0-rc3

### ISSUE THREAD

**Issue by VRcontrib** [galister/X11Overlay#17]
As of WlxOverlay v1.4.0-rc3, the circle used as a cursor is huge (especially compared to earlier versions). Is this intentional? If so, could there be a config option implemented to bring the smaller cursor back, or an option to customize the size of the cursor? If not, which I imagine is the case because it is incredibly difficult to use, I can send images of what is happening and provide any other information necessary.

**Comment by galister** [comment]
we've switched to using a rendered-on cursor instead of the overlay-based one. the size now depends on the resolution of the screen you're using it on.

mind dropping some before and after screenshots?
also are you on X11 or wayland?
what resolution?

**Comment by VRcontrib** [comment]
> we've switched to using a rendered-on cursor instead of the overlay-based one. the size now depends on the resolution of the screen you're using it on.

Thanks for the information!

> mind dropping some before and after screenshots?

No problem, I'll post them later today. I'm not at my VR machine right now.

> also are you on X11 or wayland?

I'm on X11, and I have some configuration issues with my system so I cannot try wayland as of now.

> what resolution?

1920x1080

**Comment by galister** [comment]
let me know if the new pre-release is any better: https://github.com/galister/WlxOverlay/releases/tag/v1.4.0-rc4

**Comment by VRcontrib** [comment]
Thank you! I'll try that release when I get home. I'm sorry I didn't get back to you with the screenshots yesterday, if the issue persists I'll still send them.

**Comment by VRcontrib** [comment]
Sorry it's been a while, I really appreciate your patience.

This issue has been resolved in WlxOverlay-1.4.0-rc4, thank you!
