### ISSUE TITLE
Cursor on wrong desktop.

### ISSUE THREAD

**Issue by 2-3-5-41** [galister/X11Overlay#19]
## Description
With more than one display, the cursor will hover on a different display until you re-arrange display cables.

## Side Note(s)
I don't think this is a wlxoverlay specific issue, but this could just be something to keep in mind. 

## System Info
**OS**: Arch Linux x86_64
**Kernel**: 6.4.12-arch1-1
**DE**: Plasma 5.27.7
**WM**: kwin

**Comment by galister** [comment]
Try removing your Pipewire tokens: `rm ~/.config/wlxoverlay/*.token`

Next time you launch, you'll get the screen share popups. Be sure to select them in the same order as they're being asked. 

You should be seeing desktop notifications for guidance, but if that doesn't work, try running it from the terminal once.

**Comment by 2-3-5-41** [comment]
This fixed it, however, KDE probably isn't asking the same thing as other popups, but it's not difficult to retry to get them in order.
