### ISSUE TITLE
Feature Request: Integration with SteamVR Overlay/Plugin management for autostarting

### ISSUE THREAD

**Issue by kzdixon** [galister/X11Overlay#2]
Thanks for creating an overlay replacement as a workaround for the sad state of affairs SteamVR on Linux leaves us with!

I was curious if you'd be be able to to get it to register with and be eligible for autostarting via SteamVR's Overlay/Plugin manager as per some of the vague instructions I stumbled upon here.

https://steamcommunity.com/app/250820/discussions/7/1750147265264506783/

> You basically need to add an application manifest via vr::VRApplications()->AddApplicationManifest() and set your application to auto launch vr::VRApplications()->SetApplicationAutoLaunch().

Pic of the Overlay/Plugin manager for reference:
![2023-01-14-03:28:50-screenshot](https://user-images.githubusercontent.com/10300293/212463473-8c5d5966-b47c-4252-940f-132e4234543e.png)

**Comment by galister** [comment]
I did add this but it just won't show up, I'm guessing due to the fact that it's not a steam application? Have you seen external application be able to use this?

**Comment by kzdixon** [comment]
I personally haven't added any external applications but I know OVR Advanced Settings has a repo; Never tried seeing if it shows up when installed outside of steam with the manifests and all added in though.

**Comment by galister** [comment]
Hmm well, I use OVRAS standalone; I downloaded it separately and launch it just like X11Overlay, and it doesn't show up in there either.

**Comment by CobaltSpace** [comment]
I think there is something that has to be added to steamvr config to auto launch an overlay. I'm not sure of the specifics, but https://github.com/Supreeeme/vrdio does this.

**Comment by galister** [comment]
works as of 1.2.0, see the release notes for wayland-specifics
