### ISSUE TITLE
The video menu does nothing.

### ISSUE THREAD

**Issue by VRcontrib** [galister/X11Overlay#21]
As of [WlxOverlay v1.4.0-rc5](https://github.com/galister/WlxOverlay/releases/tag/v1.4.0-rc5), the video menu doesn't do anything on my system. When I select the buttons in the menu, the colors and brightness do not change at all. I've checked that they do not change on the SteamVR overlay, WlxOverlay, and multiple games (VRChat, Beat Saber, H3VR, Synth Riders, Electronauts, and a Test Project in Godot).

Using X11
Arch Linux
SteamVR 1.26.7
WlxOverlay 1.4.0-rc5

I will test on beta SteamVR soon and report if it works properly or not here.

Thank you,
A VRContrib Contributor

**Comment by galister** [comment]
All the video tab does is change the HMD color gain settings in SteamVR:
```
HmdDisplayColorGainR_Float
HmdDisplayColorGainG_Float
HmdDisplayColorGainB_Float
```
(OVRAS does the same)

If it doesn't work then it's due to SteamVR not supporting it for your specific setup. As far as I'm aware, it's not supported with linux-vulkan-async enabled, and also not supported anymore on Windows.

**Comment by ghost** [comment]
Thanks! It's very unfortunate that it isn't supported very well :(. Could you please consider adding that to the project wiki so future users who encounter this issue are aware of it?

Thank you,
A VRContrib Contributor
